README.md

fix formula problem

---

docs/source/quick_start/md/quick_start.md

fix bug in quick_start

---

examples/stgcn/README.md
examples/stgcn/data_loader/__init__.py
examples/stgcn/data_loader/data_utils.py
examples/stgcn/data_loader/graph.py
examples/stgcn/main.py
examples/stgcn/models/model.py
examples/stgcn/models/tester.py
examples/stgcn/utils/math_utils.py
pgl/graph.py

1, Graph dump node_feat and edge_feat;
2, add stgcn model.

add stgcn model

---

examples/distribute_metapath2vec/README.md
examples/distribute_metapath2vec/cloud_run.sh
examples/distribute_metapath2vec/cluster_train.py
examples/distribute_metapath2vec/config.yaml
examples/distribute_metapath2vec/data_process.py
examples/distribute_metapath2vec/graph.py
examples/distribute_metapath2vec/job.sh
examples/distribute_metapath2vec/local_config
examples/distribute_metapath2vec/model.py
examples/distribute_metapath2vec/mp_reader.py
examples/distribute_metapath2vec/multi_class.py
examples/distribute_metapath2vec/utils.py
examples/distribute_metapath2vec/utils.sh
examples/distribute_metapath2vec/walker.py
ogb_examples/graphproppred/main_pgl.py
ogb_examples/linkproppred/main_pgl.py
pgl/__init__.py
pgl/contrib/ogb/graphproppred/mol_encoder.py
pgl/contrib/ogb/linkproppred/dataset_pgl.py
pgl/graph.py
pgl/graph_kernel.pyx
pgl/graph_wrapper.py
pgl/layers/__init__.py
pgl/layers/graph_pool.py
pgl/tests/test_hetergraph.py

1, add distribute metapath2vec;
2, fix bug in pgl;
3, add num_edge to holder list;
4, update ogb dataset.

update to 1.0.2

---

pgl/contrib/__init__.py

add __init__.py file

---

examples/kg/README.md
examples/kg/data_loader.py
examples/kg/evalutate.py
examples/kg/main.py
examples/kg/model/Model.py
examples/kg/model/RotatE.py
examples/kg/model/TransE.py
examples/kg/model/TransR.py
examples/kg/model/__init__.py
examples/kg/model/utils.py
examples/kg/mp_mapper.py
examples/kg/run.sh

Merge the KG tools to pgl, include the some models

Add the KG tools to pgl, include the model of transE TransR RotatE

---

examples/gin/Dataset.py
examples/gin/README.md
examples/gin/dataloader.py
examples/gin/main.py
examples/gin/model.py

add gin example

---

pgl/layers/conv.py

fix bug of elementwise_mul error

fix bug of elementwise_mul error

---

examples/gin/model.py
ogb_examples/graphproppred/README.md
ogb_examples/graphproppred/mol/README.md
ogb_examples/graphproppred/mol/args.py
ogb_examples/graphproppred/mol/data/__init__.py
ogb_examples/graphproppred/mol/data/base_dataset.py
ogb_examples/graphproppred/mol/data/dataloader.py
ogb_examples/graphproppred/mol/data/splitters.py
ogb_examples/graphproppred/mol/hiv_config.yaml
ogb_examples/graphproppred/mol/main.py
ogb_examples/graphproppred/mol/model.py
ogb_examples/graphproppred/mol/mol_encoder.py
ogb_examples/graphproppred/mol/monitor/train_monitor.py
ogb_examples/graphproppred/mol/optimization.py
ogb_examples/graphproppred/mol/pcba_config.yaml
ogb_examples/graphproppred/mol/utils/__init__.py
ogb_examples/graphproppred/mol/utils/args.py
ogb_examples/graphproppred/mol/utils/cards.py
ogb_examples/graphproppred/mol/utils/config.py
ogb_examples/graphproppred/mol/utils/fp16.py
ogb_examples/graphproppred/mol/utils/init.py
ogb_examples/graphproppred/ogbg_ppi.py
pgl/layers/conv.py

add graph classification of molecule dataset for ogb.

add graph classification of molecule dataset for ogb

---

ogb_examples/graphproppred/mol/README.md
ogb_examples/graphproppred/mol/hiv_config.yaml
ogb_examples/graphproppred/mol/pcba_config.yaml

update README and config for ogb mol graph classification

update README and config for ogb mol graph classification

---

ogb_examples/graphproppred/mol/README.md
ogb_examples/graphproppred/mol/args.py
ogb_examples/graphproppred/mol/hiv_config.yaml
ogb_examples/graphproppred/mol/main.py
ogb_examples/graphproppred/mol/pcba_config.yaml

update mol task for ogb

---

docs/source/quick_start/md/quick_start_for_heterGraph.md

remove contrib in hetergraph

---

examples/erniesage/learner.py
ogb_examples/graphproppred/mol/monitor/train_monitor.py
ogb_examples/linkproppred/ogbl-ppa/monitor/train_monitor.py
pgl/utils/log_writer.py
requirements.txt

python2 using tensorboardX, python3 using VisualDL.

Function add: add the VisualDL log writer for pgl

---

ogb_examples/nodeproppred/ogbn-arxiv/README.md
ogb_examples/nodeproppred/ogbn-arxiv/args.py
ogb_examples/nodeproppred/ogbn-arxiv/dataloader/__init__.py
ogb_examples/nodeproppred/ogbn-arxiv/dataloader/base_dataloader.py
ogb_examples/nodeproppred/ogbn-arxiv/dataloader/ogbn_arxiv_dataloader.py
ogb_examples/nodeproppred/ogbn-arxiv/model.py
ogb_examples/nodeproppred/ogbn-arxiv/monitor/__init__.py
ogb_examples/nodeproppred/ogbn-arxiv/monitor/train_monitor.py
ogb_examples/nodeproppred/ogbn-arxiv/run.sh
ogb_examples/nodeproppred/ogbn-arxiv/train.py
ogb_examples/nodeproppred/ogbn-arxiv/utils/__init__.py
ogb_examples/nodeproppred/ogbn-arxiv/utils/args.py
ogb_examples/nodeproppred/ogbn-arxiv/utils/init.py
ogb_examples/nodeproppred/ogbn-arxiv/utils/to_undirected.py

We train our models for 100 epochs and report the **acc** on the test dataset.
|dataset|mean|std|#experiments|
|-|-|-|-|
|ogbn-arxiv|0.7197|0.0024|16|

Ogbn-arxiv example for PGL

---

ogb_examples/nodeproppred/ogbn-arxiv/dataloader/ogbn_arxiv_dataloader.py
pgl/graph_kernel.pyx
pgl/sample.py
pgl/tests/test_graph_saint_sample.py

add graphsaint support
(暂时未支持 graphsaint  normalization)

add graphsaint support

---

ogb_examples/nodeproppred/unipm/README.MD
ogb_examples/nodeproppred/unipm/dataloader/base_dataloader.py
ogb_examples/nodeproppred/unipm/dataloader/ogb_products_dataloader.py
ogb_examples/nodeproppred/unipm/main_arxiv.py
ogb_examples/nodeproppred/unipm/main_product.py
ogb_examples/nodeproppred/unipm/main_protein.py
ogb_examples/nodeproppred/unipm/model.py
ogb_examples/nodeproppred/unipm/module/transformer_gat_pgl.py
ogb_examples/nodeproppred/unipm/partition.py
ogb_examples/nodeproppred/unipm/requirements.txt
ogb_examples/nodeproppred/unipm/utils.py

add UniPM 

---

examples/GATNE/model.py
pgl/heter_graph.py
pgl/tests/test_MmapHeterGraph.py

add mmap on hetergraph

---

README.md
README.zh.md

[doc]: update README

---

README.md
README.zh.md

add the web site

---

examples/deepwalk/deepwalk.py
examples/node2vec/node2vec.py

fix deepwalk on windows

---

course/README.zh.md

add the pgl course

---

README.md
README.zh.md

add course link

---

README.md
course/README.md

update the ppt of the second course.

update the ppt of the second course.

---

course/README.md

update the ppt of the third course.

update the ppt of the third course.

---

course/README.md

update the ppt of the fourth course.

update the ppt of the fourth course.

---

course/README.md

update the ppt of the fifth course.

update the ppt of the fifth course.

---

pgl/utils/data/__init__.py
pgl/utils/data/dataloader.py
pgl/utils/data/dataset.py
pgl/utils/data/sampler.py

[fix]: fix bug of hadoop dataset

---

pgl/__init__.py
pgl/heter_graph.py
tests/test_hetergraph.py

add heter graph

---

legacy/examples/SAGPool/README.md

* change the link of data storage.

[DOC] Update SAGPool data the new bos link.

---

examples/gin/model.py
pgl/graph.py
pgl/nn/functional/graph_op.py
pgl/nn/pool.py

add graph_pool function

---

pgl/distributed/__init__.py
pgl/distributed/dist_graph.py
pgl/distributed/helper.py
pgl/distributed/launch.py
tests/test_dist_cpu_graph.py

add distributed graph engine

---

ogb_examples/lsc/PCQM4M/README.md
ogb_examples/lsc/PCQM4M/conv.py
ogb_examples/lsc/PCQM4M/dataset.py
ogb_examples/lsc/PCQM4M/gnn.py
ogb_examples/lsc/PCQM4M/main_gnn.py
ogb_examples/lsc/PCQM4M/mol_encoder.py
ogb_examples/lsc/PCQM4M/test_inference_gnn.py

add ogb_lsc graph regression baseline

add ogb_lsc graph regression baseline

---

docs/source/conf.py
pgl/__init__.py
pgl/distributed/__init__.py
pgl/math.py
tests/test_math.py

fix bug of segment softmax

---

pgl/distributed/dist_graph.py

node batch iterate step by step instead of batch by batch.

node batch iterate step by step

---

docs/source/conf.py
pgl/__init__.py

update version to 2.1.5

---

.github/ISSUE_TEMPLATE/----.md
.github/PULL_REQUEST_TEMPLATE.md

New features 
Others
Add PGL PR, ISSUE template.

[TEMPLATE] Add PGL PR, ISSUE template.

---

ogb_examples/nodeproppred/unimp/main_arxiv_large.py

Bug fixes
Models: Unimp demo
import errors

fix a bug in unimp

---

examples/kddcup2021/MAG240M/r_unimp/models/r_unimp.py
examples/kddcup2021/MAG240M/r_unimp/r_unimp_multi_gpu_train.py

Bug fixes
APIs
resolve hard code for m2v_dim while creating m2v_feature in r_unimp models initialization.

resolve hard code for m2v_dim

---

pgl/bigraph.py

Bug fixes
Framework
Fix typos in bigraph.

fix typos in bigraph

---

examples/lightgcn/README.md
examples/lightgcn/dataloader.py
examples/lightgcn/model.py
examples/lightgcn/train.py
examples/lightgcn/utils.py
examples/ngcf/README.md
examples/ngcf/dataloader.py
examples/ngcf/model.py
examples/ngcf/train.py
examples/ngcf/utils.py
pgl/nn/conv.py

others
others
add lightgcn and ngcf

add lightgcn and ngcf

---

examples/lightgcn/README.md
examples/lightgcn/dataloader.py
examples/ngcf/README.md
examples/ngcf/dataloader.py

others
others
add download link of datasets of lightgcn and ngcf

add download link of datasets of lightgcn and ngcf

---

setup.py

fixed compiled in windows

---

setup.py

fixed macos with metis

---

setup.py

Metis partition third party

---

docs/source/introduction/introduction.md

Bug fixes
Docs
Change relative path to absolute path in readthedocs.

fix bug of docs

---

pgl/utils/helper.py

Bug fixes
Others
add return value in unique_segment

add return value in unique_segment

---

apps/GNNAutoScale/README.md

Other
Docs
Change version of paddlepaddle-gpu.

Fix GNNAutoScale paddlepaddle-gpu version

---

README.md
README.zh.md
pgl/math.py

Others
Others
Change segment ops to incubate api.

[API] Change segment ops to incubate api. V2

---

pgl/utils/mp_reader.py

Bug fixes
Others
Fix issue: https://github.com/PaddlePaddle/PGL/issues/305

Add multiprocessing default start method

---

pgl/distributed/__init__.py
pgl/distributed/dist_graph.py
tests/test_dist_cpu_graph.py

Function optimization
APIs
update the API of neighbors samping responding to graph engine.

update the API of neighbors samping responding to graph engine

---

pgl/__init__.py

remove distributed in __init__.py

---

examples/graph_based_clustering_demo/README.md
examples/graph_based_clustering_demo/config.yaml
examples/graph_based_clustering_demo/dataset.py
examples/graph_based_clustering_demo/kmeans_clustering.py
examples/graph_based_clustering_demo/model.py
examples/graph_based_clustering_demo/train.py

Others
Models
add graph based clustering demo

graph based clustering demo

---

apps/Graph4Rec/README.md
apps/Graph4Rec/env_run/src/models/layers.py
apps/Graph4Rec/env_run/src/models/model.py
apps/Graph4Rec/user_configs/gatne.yaml

Others
Models
add GATNE model in Graph4Rec

add GATNE model

---

.gitmodules

add stream partitioner

---

docs/source/conf.py
pgl/__init__.py
pgl/distributed/dist_graph.py

Bug fixes
Others
fix bug in dist_graph

fix bug in dist_graph

---

docs/source/conf.py
pgl/__init__.py

Others
Others
update version to 2.2.2

update version to 2.2.2

---

apps/Graph4Rec/env_run/src/datasets/dataset.py
apps/Graph4Rec/env_run/src/datasets/node.py

Bug fixes
Others
add infer_node_generator for inference to save all node embeddings.

add infer_node_generator

---

apps/Graph4Rec/env_run/src/models/layers.py
apps/Graph4Rec/user_configs/graphsage.yaml

- graphsage.yaml:
- GraphsageSumConv -> GraphSageSumConv;
- models.layers.py:
- line22: GraphSageConv -> GraphSageSumConv;
- line54: GraphSageConv -> GraphSageMeanConv;
另提示:paddlepaddle-gpu==2.2.2需要搭配pgl==2.1.5

Graph4Rec - GraphSage Task,源码报错修改:

---

apps/Graph4KG/config.py
apps/Graph4KG/dataset/reader.py
apps/Graph4KG/eval.py
apps/Graph4KG/train.py
examples/AITISA/kg/README.md
examples/AITISA/kg/convert_tools.py

Function optimization 
Models
add the eval script for the graph4kg

add the eval script for the graph4kg

---

apps/Graph4KG/config.py
apps/Graph4KG/dataset/reader.py
apps/Graph4KG/dist_train.py

Bug fixes
Models
- Fix bug during creating and loading dictionary

[graph4kg] fix bug in reader

---

pgl/__init__.py

Others
Others
Add paddlepaddle version warning.

Add paddle version warning

---

examples/rgcn/Dataset.py
examples/rgcn/README.md
examples/rgcn/layer.py
examples/rgcn/train.py

New features
Models
RGCN: Modeling Relational Data with Graph Convolutional Networks
[RGCN](http://arxiv.org/abs/1703.06103) is a graph convolutional networks applied in heterogeneous graph.

Static stable

---

pgl/math.py
pgl/utils/helper.py
pgl/utils/op.py

Bug fixes
APIs
[Eager]Replace all core.ops with _C_ops
Paddle主框架重构了新动态图，所有的pybind或者python C 方法都将通过`_C_ops.XX`来替换`core.ops.XX`

[Eager]Replace all core.ops with _C_ops

---

.github/workflows/build_and_upload_PyPI.yml

Others
Others
Update  build_and_upload_PyPI

Update  build_and_upload_PyPI

---

docs/source/conf.py
pgl/__init__.py
setup.py

update version to 2.2.3post0

---

apps/Graph4KG/examples/REP/rep.py

Small bugfix for REP

---

apps/Graph4KG/dataset/reader.py
pgl/utils/shared_embedding.py
tests/test_shared_embedding.py

- Fix type error in ``step`` function.
- Update unittest code for current SharedEmbedding.

[SharedEmb] fix bug in step function and unittest

---

apps/GNNAutoScale/utils.py
apps/Graph4Rec/README.md
apps/Graph4Rec/env_run/src/dist_cpu_infer.py
apps/Graph4Rec/env_run/src/dist_cpu_train.py
apps/Graph4Rec/env_run/src/models/model.py
examples/deepwalk/README.md
examples/deepwalk/train_distributed_cpu.py
examples/deepwalk/train_distributed_gpu.py
examples/gat/README.md
examples/graphsage/train_distributed_cpu.py
examples/kddcup2021/MAG240M/r_unimp/README.md
examples/lightgcn/train.py
examples/ngcf/train.py
examples/node2vec/train_distributed_cpu.py
pgl/bigraph.py
pgl/distributed/dist_graph.py
pgl/graph.py
pgl/math.py
pgl/partition.py
pgl/utils/edge_index.py
pgl/utils/helper.py
pgl/utils/mp_reader.py
pgl/utils/op.py
pgl/utils/shared_embedding.py
pgl/utils/stream_pool.py

Others
Others
Delete fluid apis.
- TBD: Need to run test.

Delete fluid apis

---

.github/workflows/manully_test_PYPI.yml

update work flow

---

examples/global_pool/README.md
examples/global_pool/dataset.py
examples/global_pool/global_pool.py
examples/global_pool/main.py
examples/sag_pool/README.md
examples/sag_pool/dataset.py
examples/sag_pool/main.py
examples/sag_pool/model.py
pgl/nn/pool.py
pgl/utils/transform.py
tests/test_pool.py

- fix bugs in to_dense_batch (pgl.utils.transforms) .
- fix bugs in GlobalPool (pgl.nn.pool).
- global pool examples

add global pool example

---

examples/citation_benchmark/README.md
examples/citation_benchmark/config/gatv2.yaml
examples/citation_benchmark/config/gpr.yaml
examples/citation_benchmark/model.py
examples/gatv2/README.md
examples/gatv2/train.py
examples/gpr/README.md
examples/gpr/train.py
pgl/nn/conv.py

add two models to nn.conv, example, and citation_benchmark

add GATv2 & GPRGNN model

---

examples/gnn_depoly/README.md
examples/gnn_depoly/models/__init__.py
examples/gnn_depoly/models/base_conv.py
examples/gnn_depoly/models/conv/__init__.py
examples/gnn_depoly/models/conv/gat_conv.py
examples/gnn_depoly/models/conv/gcn_conv.py
examples/gnn_depoly/models/conv/sage_conv.py
examples/gnn_depoly/models/gat.py
examples/gnn_depoly/models/gcn.py
examples/gnn_depoly/models/graphsage.py
examples/gnn_depoly/node_classification_with_full_graph/export_model.py
examples/gnn_depoly/node_classification_with_full_graph/python_deploy.py
examples/gnn_depoly/node_classification_with_full_graph/train.py
examples/gnn_depoly/node_classification_with_sampling/dataset.py
examples/gnn_depoly/node_classification_with_sampling/export_model.py
examples/gnn_depoly/node_classification_with_sampling/python_deploy.py
examples/gnn_depoly/node_classification_with_sampling/train.py

TODO：
1. 待将GATConv转换为geometric中相应的API；
2. 精简代码；
3. 撰写README。

Add GNN deployment

---

apps/Graph4KG/dist_train.py
apps/Graph4KG/train.py
apps/Graph4Rec/env_run/src/train.py
docs/source/quick_start/quick_start.md
docs/source/quick_start/working_with_hetergraph.md
examples/NeurIPS2022-OGB-Challenge/MAG240M/dataset/new_dataset_p2p.py
examples/NeurIPS2022-OGB-Challenge/MAG240M/r_unimp_train_p2p.py
examples/deepwalk/multi_class.py
examples/deepwalk/train.py
examples/graph_based_clustering_demo/train.py
examples/kddcup2021/MAG240M/r_unimp/r_unimp_multi_gpu_train.py
examples/kddcup2022/wpf_baseline/main.py
examples/metapath2vec/train.py
examples/node2vec/multi_class.py
examples/node2vec/train.py
examples/rgcn/train.py
ogb_examples/lsc/MAG240M/lsc_node.py
ogb_examples/lsc/MAG240M/lsc_node_hetegraph.py
tests/test_bigraph.py
tests/test_graph.py
tutorials/quick_start.ipynb
tutorials/working_with_hetergraph.ipynb

1. 代码中所有的``x.numpy()[0]``，框架同学建议修改为 `float(x)`或者`int(x)`等，以适配0维Tensor的场景。`float(x)`的写法在`x`为1D或0D Tensor时均能正常使用。

Change 0 dim tensor usage

---

examples/gat/train.py
examples/gcn/train.py
examples/sgc/train.py
examples/ssgc/train.py

Fixed `epoch` option for examples of GAT, GCN, SGC, and SSGC
修复GAT、GCN、SGC、SSGC范例中`epoch` 选项失效问题

Fixed `epoch` option for examples of GAT, GCN, SGC, and SSGC

---

apps/PGLBox/README.md
apps/PGLBox/docker/Dockerfile
apps/PGLBox/docker/build.sh

update Dockerfile of PGLBox

---

apps/PGLBox/sharding_tool/README.md
apps/PGLBox/sharding_tool/graph_sharding.py
apps/PGLBox/sharding_tool/run_sharding.sh
apps/PGLBox/train.sh

add README for graph sharding

---

apps/PGLBox/README.md
apps/PGLBox/docker/Dockerfile
apps/PGLBox/docker/README.md
apps/PGLBox/src/cluster_train_and_infer.py
apps/PGLBox/src/config_fleet.py
apps/PGLBox/src/dataset.py
apps/PGLBox/src/distributed_program.py
apps/PGLBox/src/embedding.py
apps/PGLBox/src/env.sh
apps/PGLBox/src/graph.py
apps/PGLBox/src/helper.py
apps/PGLBox/src/models/__init__.py
apps/PGLBox/src/models/auto_heter_gnn.py
apps/PGLBox/src/models/gnn_model.py
apps/PGLBox/src/models/layers.py
apps/PGLBox/src/models/loss.py
apps/PGLBox/src/models/model_util.py
apps/PGLBox/src/place.py
apps/PGLBox/src/util.py
apps/PGLBox/user_configs/lightgcn.yaml
apps/PGLBox/user_configs/metapath.yaml

Add pglbox v2

---

apps/PGLBox/src/cluster_train_and_infer.py
apps/PGLBox/src/dataset.py
apps/PGLBox/src/graph.py
apps/PGLBox/src/models/gnn_model.py
apps/PGLBox/user_configs/lightgcn.yaml
apps/PGLBox/user_configs/metapath.yaml

using batch_size instead of batch_node_size

using batch_size instead of batch_node_size

---

apps/PGLBox/README.md
apps/PGLBox/demo_configs/mag240m_metapath2vec.yaml

1. Add demo_config for mag240m
2. Fix README

Add demo_config for mag240m

---

apps/PGLBox/src/models/model_util.py

1. Add missing code in model_util.py

[PGLBox] Add missing code

---

examples/bernnet/README.md
examples/bernnet/model.py
examples/bernnet/propagation.py
examples/bernnet/train.py
examples/bernnet/utils.py
examples/chebnetii/README.md
examples/chebnetii/model.py
examples/chebnetii/ogb/large_train.py
examples/chebnetii/ogb/model.py
examples/chebnetii/ogb/processing.py
examples/chebnetii/ogb/utils.py
examples/chebnetii/propagation.py
examples/chebnetii/train.py
examples/chebnetii/utils.py

I add examples of two models (bernnet and chebnetII).

Add chebnetii and bernnet

---

pgl/nn/functional/graph_op.py

Fix edge_softmax for static graph mode

---

apps/Graph4Rec/env_run/src/dist_cpu_infer.py
examples/NeurIPS2022-OGB-Challenge/MAG240M/dataset/new_dataset_p2p.py
examples/NeurIPS2022-OGB-Challenge/MAG240M/dist_feat.py
examples/gnn_depoly/node_classification_with_sampling/train.py
pgl/graph.py
pgl/utils/edge_index.py
pgl/utils/helper.py

注：
1. legacy 文件夹内为1.8静态图版本，不再迭代
2. ogb_examples内为1.8静态图版本，不再迭代
3. apps 文件夹中的 PGLBox 与内部版本对应，需要固定 Paddle 版本，等内部版本更新后再对外部 github 代码进行更新。

Remove fluid

---

.github/workflows/build_and_upload_PyPI.yml
.github/workflows/manully_test_PYPI.yml

Fix github workflow

---

.github/workflows/build_and_upload_PyPI.yml
.github/workflows/manully_test_PYPI.yml
docs/source/conf.py

remove py39 in github action
